# Generated by Django 6.0 on 2025-12-24 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 24, 7, 37, 35, 615285)),
        ),
    ]
