# Generated by Django 6.0 on 2026-01-09 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 9, 6, 23, 36, 397014)),
        ),
    ]
